import { GameModeConfig } from "../types";

export const GAME_MODES: Record<string, GameModeConfig> = {
  classic: {
    id: "classic",
    name: "Classic Range",
    tagline: "Speed, precision, and combo chains.",
    description: "Hit as many targets as possible within the time limit. Chain consecutive hits to build huge score multipliers.",
    badge: "Most Popular",
    iconName: "Target",
    defaultDuration: 45,
    hasAmmo: true,
    maxAmmo: 12,
    reloadTime: 900,
    scoringRules: {
      baseHit: 100,
      smallHit: 180,
      criticalHit: 280,
      comboStepBonus: 50,
      missPenalty: 0,
      hazardPenalty: 150,
    },
  },
  "time-attack": {
    id: "time-attack",
    name: "Time Attack",
    tagline: "Race the clock to target score.",
    description: "Reach the target score quota before the countdown reaches zero. Rapid bullseyes grant bonus seconds!",
    badge: "High Intensity",
    iconName: "Zap",
    defaultDuration: 30,
    targetScoreGoal: 8000,
    hasAmmo: true,
    maxAmmo: 10,
    reloadTime: 800,
    scoringRules: {
      baseHit: 120,
      smallHit: 220,
      criticalHit: 350,
      comboStepBonus: 60,
      missPenalty: 0,
      hazardPenalty: 200,
    },
  },
  survival: {
    id: "survival",
    name: "Survival Mode",
    tagline: "Endure escalating waves of targets.",
    description: "Targets spawn faster and become aggressive. Missing shots or letting targets expire inflicts damage on your shield.",
    badge: "Hardcore",
    iconName: "ShieldAlert",
    defaultDuration: 90,
    hasHealth: true,
    maxHealth: 100,
    hasAmmo: true,
    maxAmmo: 12,
    reloadTime: 950,
    scoringRules: {
      baseHit: 150,
      smallHit: 250,
      criticalHit: 400,
      comboStepBonus: 75,
      missPenalty: 10, // 10 damage
      hazardPenalty: 25, // 25 damage
    },
  },
  precision: {
    id: "precision",
    name: "Precision Sniper",
    tagline: "Every bullet matters. 100% accuracy required.",
    description: "Micro-targets with fleeting lifespans. Misses break your combo instantly and penalize your final accuracy rating heavily.",
    badge: "Skill Test",
    iconName: "Crosshair",
    defaultDuration: 40,
    precisionRequired: true,
    hasAmmo: true,
    maxAmmo: 6,
    reloadTime: 1100,
    scoringRules: {
      baseHit: 150,
      smallHit: 300,
      criticalHit: 500,
      comboStepBonus: 100,
      missPenalty: 50,
      hazardPenalty: 300,
    },
  },
};
